#!/bin/bash

filename=$3
version=$2
path=$PWD

tmpdir=$(mktemp -d);
(
cd $tmpdir;
tar -zxf $path/$filename;
rm -f */Graphics/CODE2000.*;
rm -f */Graphics/FreeSans.ttf;
#rm -rf */CPAN;
#rm -rf */Bin;
rm -rf */Firmware/*.bin;
find * -regex '.*\.\(png\|gif\|html\)$$' -exec chmod -x '{}' ';';
tar --create --gzip --file logitechmediaserver-$version.dfsg1.tar.gz *;
)
mv $tmpdir/logitechmediaserver-$version.dfsg1.tar.gz .;
rm -rf $tmpdir;

