#!/bin/sh

# $Id$

# preinst script for SqueezeCenter

set -e

case "$1" in
	upgrade)
	# firmware cleanup
	if dpkg --compare-versions "$2" lt-nl "7.3.1.dfsg-5"; then
		if [ -L /usr/share/squeezecenter/Firmware ]; then
			rm -f /usr/share/squeezecenter/Firmware
			mkdir /usr/share/squeezecenter/Firmware
		fi
		if [ -d /var/lib/squeezecenter/Firmware ]; then
			rm -rf /var/lib/squeezecenter/Firmware/*.bin
		fi
	fi
esac

