#!/bin/sh
# prerm script for bubba-horde

set -e
. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm.mysql 
dbc_go squeezecenter $@

if [ -x "/etc/init.d/squeezecenter" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d squeezecenter stop || exit $?
        else
                /etc/init.d/squeezecenter stop || exit $?
        fi
fi

#DEBHELPER#

exit 0
