Slim 					/usr/share/perl5
lib 					/usr/share/squeezecenter
Graphics				/usr/share/squeezecenter
IR						/usr/share/squeezecenter
SQL						/usr/share/squeezecenter
strings.txt				/usr/share/squeezecenter
MySQL					/usr/share/squeezecenter
Firmware				/usr/share/squeezecenter
*.conf					/etc/squeezecenter

#Essential skins
HTML/Default			/usr/share/squeezecenter/HTML
HTML/EN					/usr/share/squeezecenter/HTML
